[project]
name = 'Transparent-Public-Infrastructure-Project-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.contractor-bidding]
path = 'contracts/contractor-bidding.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-proposal]
path = 'contracts/project-proposal.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
